/* 唐揚げ防衛隊 - 設定 */
window.KD = window.KD || {};

KD.Config = {
  world: {
    groundRadius: 420,
    fogNear: 120,
    fogFar: 420,
    skyColor: 0x0a1024,
    ambientColor: 0x33415e,
    ambientIntensity: 0.9,
    moonColor: 0x8fa8ff,
    moonIntensity: 0.55,
  },

  player: {
    speed: 26,
    sprintSpeed: 40,
    accel: 90,
    hp: 100,
    eyeHeight: 3.4,
    radius: 1.6,
    camDist: 11,
    camHeight: 5,
    camPitchMin: -0.9,
    camPitchMax: 0.7,
    camYawSens: 0.0022,
    camPitchSens: 0.0019,
    invulnAfterHit: 0.8,
  },

  weapon: {
    damage: 12,
    fireInterval: 0.11,
    magSize: 30,
    reloadTime: 1.6,
    bulletSpeed: 150,
    bulletLife: 2.2,
    spread: 0.012,
    muzzleFlashTime: 0.05,
    tracerColor: 0x7adfff,
  },

  base: {
    hp: 1000,
    panRadius: 10,
    panRimHeight: 3.2,
    pedestalHeight: 2.2,
    eatRadius: 15,
    tareZoneRadius: 46,
    tareChargeTime: 0.9,
    tareDuration: 9,
    tareDamageMult: 2.0,
    tareSpeedMult: 0.55,
    sprayInterval: 1.6,
    sprayNozzles: 4,
  },

  enemies: {
    raptor: {
      name: "ガララプター",
      motif: "恐竜・リザード",
      img: "assets/kaiju_raptor.png",
      hp: 130,
      speed: 15,
      lungeSpeed: 42,
      lungeWindup: 0.75,
      lungeCooldown: 3.2,
      attackRange: 7,
      damage: 8,
      attackInterval: 1.6,
      billboardH: 34,
      score: 100,
      attack: "lunge",
      fly: false,
    },
    ptera: {
      name: "プテラドン",
      motif: "恐竜・翼竜",
      img: "assets/kaiju_ptera.png",
      hp: 170,
      speed: 17,
      diveSpeed: 55,
      diveWindup: 1.0,
      lungeCooldown: 3.8,
      flyHeight: 62,
      attackRange: 9,
      damage: 12,
      attackInterval: 2.2,
      billboardH: 40,
      billboardW: 56,
      score: 200,
      attack: "dive",
      fly: true,
    },
    squid: {
      name: "スクイドラ",
      motif: "海洋・イカ",
      img: "assets/kaiju_squid.png",
      hp: 240,
      speed: 9,
      tentacleRange: 34,
      tentacleWindup: 1.1,
      lungeCooldown: 4.2,
      attackRange: 8,
      damage: 16,
      attackInterval: 2.6,
      billboardH: 48,
      score: 300,
      attack: "tentacle",
      fly: false,
    },
    mosa: {
      name: "モサゴロザ",
      motif: "海洋・海竜",
      img: "assets/kaiju_mosa.png",
      hp: 210,
      speed: 12,
      chargeSpeed: 50,
      chargeTime: 1.4,
      chargeCooldown: 5.0,
      attackRange: 8,
      damage: 14,
      attackInterval: 2.4,
      billboardH: 44,
      score: 250,
      attack: "charge",
      fly: false,
    },
    tera: {
      name: "テラゴロザウルス",
      motif: "恐竜・T-REX",
      img: "assets/kaiju_tera.png",
      hp: 1600,
      speed: 8,
      stompRange: 14,
      stompWindup: 1.2,
      lungeCooldown: 3.0,
      attackRange: 12,
      damage: 30,
      attackInterval: 2.0,
      billboardH: 64,
      score: 1500,
      attack: "stomp",
      fly: false,
      boss: true,
    },
    terax: {
      name: "テラゴロザウルス・アルファ",
      motif: "恐竜・T-REX・最終",
      img: "assets/kaiju_tera.png",
      hp: 3200,
      speed: 9,
      stompRange: 16,
      stompWindup: 1.0,
      lungeCooldown: 2.4,
      attackRange: 14,
      damage: 40,
      attackInterval: 1.7,
      billboardH: 76,
      score: 3000,
      attack: "stomp",
      fly: false,
      boss: true,
      finalBoss: true,
    },
  },

  // 10ステージ構成。boss=true のステージはボス専用BGM。dpMult はDP経済のステージ乗数
  waves: [
    { list: [["raptor", 6]], message: "ステージ1: ガララプター群出現", boss: false, dpMult: 0.5 },
    { list: [["raptor", 8], ["ptera", 3]], message: "ステージ2: 空からプテラドン", boss: false, dpMult: 0.6 },
    { list: [["raptor", 6], ["squid", 3], ["ptera", 4]], message: "ステージ3: 海の怪物スクイドラ", boss: false, dpMult: 0.7 },
    { list: [["mosa", 4], ["raptor", 8], ["squid", 3], ["ptera", 4]], message: "ステージ4: モサゴロザ突撃!", boss: false, dpMult: 0.8 },
    { list: [["tera", 1], ["raptor", 8], ["ptera", 4], ["squid", 4]], message: "ステージ5: テラゴロザウルス出現!!", boss: true, dpMult: 0.9 },
    { list: [["raptor", 8], ["ptera", 6], ["squid", 6]], message: "ステージ6: 空と海が同時襲来", boss: false, dpMult: 1.0 },
    { list: [["raptor", 8], ["ptera", 5], ["squid", 6], ["mosa", 5]], message: "ステージ7: 4種混成軍", boss: false, dpMult: 1.1 },
    { list: [["raptor", 12], ["mosa", 6], ["squid", 6], ["ptera", 6]], message: "ステージ8: 大群が迫る!", boss: false, dpMult: 1.2 },
    { list: [["raptor", 8], ["ptera", 8], ["squid", 6], ["mosa", 8]], message: "ステージ9: 街はもう限界だ!", boss: false, dpMult: 1.3 },
    { list: [["terax", 1], ["raptor", 8], ["ptera", 6], ["mosa", 6], ["squid", 4]], message: "最終ステージ: アルファ出現!!!", boss: true, dpMult: 1.4 },
  ],

  waveBreak: 12,
  spawnRingMin: 150,
  spawnRingMax: 300,
  maxEnemies: 30,

  // 防衛ポイント(DP)経済: 撃破で score/10 * dpMult を獲得
  dp: {
    perScore: 0.1,
  },

  // 強化システム: 各ライン最大Lv2、準備フェーズでコストを支払って購入
  upgrades: {
    weapon: {
      name: "武器強化",
      cost: 300,
      desc: ["威力 +25% (12→15)", "威力+・連射+20% (15→19)"],
    },
    base: {
      name: "基地防御",
      cost: 300,
      desc: ["耐久+300 & 修復200", "耐久+400 & 修復400"],
    },
    squad: {
      name: "隊員追加",
      cost: 300,
      desc: ["支援兵+1 (HP+20)", "支援兵+2 (被弾-20%)"],
    },
    turret: {
      name: "防御タレット",
      cost: 300,
      desc: ["タレット+1 (追尾)", "タレット+1・火力+25%"],
    },
  },

  audio: {
    bgm: "audio/bgm_defense.ogg",
    bgmStages: [
      "audio/bgm_stage01.ogg",
      "audio/bgm_stage02.ogg",
      "audio/bgm_stage03.ogg",
      "audio/bgm_stage04.ogg",
      "audio/bgm_stage05.ogg",
      "audio/bgm_stage06.ogg",
      "audio/bgm_stage07.ogg",
      "audio/bgm_stage08.ogg",
      "audio/bgm_stage09.ogg",
      "audio/bgm_stage10.ogg",
    ],
    amb: "audio/amb_city_night.ogg",
    sfx: {
      shoot: "audio/sfx_gun.ogg",
      hit: "audio/sfx_hit.ogg",
      roar: "audio/sfx_roar.ogg",
      death: "audio/sfx_death.ogg",
      spray: "audio/sfx_spray.ogg",
      tare: "audio/sfx_tare.ogg",
      playerHit: "audio/sfx_player_hit.ogg",
      alarm: "audio/sfx_alarm.ogg",
    },
    voice: {
      briefing: "audio/voice_briefing.ogg",
      wave: "audio/voice_wave_start.ogg",
      enemy: "audio/voice_enemy_close.ogg",
      baseHit: "audio/voice_base_hit.ogg",
      playerHit: "audio/voice_player_hit.ogg",
      boss: "audio/voice_boss.ogg",
      victory: "audio/voice_victory.ogg",
      gameover: "audio/voice_gameover.ogg",
      // オペレーター無線 (新規)
      opStage1: "audio/op_stage01.ogg",
      opStage2: "audio/op_stage02.ogg",
      opStage3: "audio/op_stage03.ogg",
      opStage4: "audio/op_stage04.ogg",
      opStage5: "audio/op_stage05.ogg",
      opStage6: "audio/op_stage06.ogg",
      opStage7: "audio/op_stage07.ogg",
      opStage8: "audio/op_stage08.ogg",
      opStage9: "audio/op_stage09.ogg",
      opStage10: "audio/op_stage10.ogg",
      opIdle1: "audio/op_idle01.ogg",
      opIdle2: "audio/op_idle02.ogg",
      opIdle3: "audio/op_idle03.ogg",
      opIdle4: "audio/op_idle04.ogg",
      opIdle5: "audio/op_idle05.ogg",
      opIdle6: "audio/op_idle06.ogg",
      opIdle7: "audio/op_idle07.ogg",
      opIdle8: "audio/op_idle08.ogg",
      opBossIn1: "audio/op_boss_in1.ogg",
      opBossIn2: "audio/op_boss_in2.ogg",
      opBossLow: "audio/op_boss_low.ogg",
      opBossDown: "audio/op_boss_down.ogg",
      opUpWeapon: "audio/op_up_weapon.ogg",
      opUpBase: "audio/op_up_base.ogg",
      opUpSquad: "audio/op_up_squad.ogg",
      opUpTurret: "audio/op_up_turret.ogg",
      opUpMax: "audio/op_up_max.ogg",
      opBaseHit2: "audio/op_base_hit2.ogg",
      opPlayerHit2: "audio/op_player_hit2.ogg",
    },
  },
};
